/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "PrestoDB",
  "tagline": "Distributed SQL Query Engine for Big Data",
  "url": "https://prestodb.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.png",
  "organizationName": "prestodb",
  "projectName": "presto",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/dmcknight/Sites/prestodb-v2/prestodb.io/sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": [
            "/Users/dmcknight/Sites/prestodb-v2/prestodb.io/src/css/bootstrap.min.css",
            "/Users/dmcknight/Sites/prestodb-v2/prestodb.io/src/css/custom.css",
            "/Users/dmcknight/Sites/prestodb-v2/prestodb.io/src/css/effects.css",
            "/Users/dmcknight/Sites/prestodb-v2/prestodb.io/src/css/ytlightbox.css"
          ]
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "logo": {
        "alt": "PrestoDB",
        "src": "img/logo-presto-white.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Get Started"
        },
        {
          "type": "dropdown",
          "label": "Learn",
          "position": "left",
          "items": [
            {
              "to": "/blog",
              "label": "Blog"
            }
          ]
        },
        {
          "to": "community",
          "label": "Community",
          "position": "left",
          "target": "_self"
        },
        {
          "to": "pathname:///docs/current/",
          "label": "Docs",
          "position": "left",
          "target": "_self"
        },
        {
          "href": "https://github.com/prestodb/presto",
          "className": "nav-icon nav-github",
          "position": "right"
        },
        {
          "href": "https://twitter.com/prestodb",
          "className": "nav-icon nav-twitter",
          "position": "right"
        },
        {
          "href": "https://prestodb.slack.com/",
          "className": "nav-icon nav-slack",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Get Started",
              "to": "/docs/intro"
            },
            {
              "to": "pathname:///docs/current/",
              "label": "Presto Docs",
              "position": "left",
              "target": "_self"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Slack",
              "href": "https://prestodb.slack.com/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/prestodb"
            },
            {
              "label": "MeetUp",
              "href": "https://www.meetup.com/topics/presto/"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/presto-foundation/"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "PrestoDB Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/prestodb/presto"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022  The Presto Foundation.<br>\n        AAll rights reserved. Presto is a registered trademark of LF Projects, LLC. <br>Please see our <a href=\"https://lfprojects.org/policies/trademark-policy/\" target=\"_blank\">Trademark Policy</a> for more\n    information.<br/>\n    <a href=\"https://lfprojects.org/policies/privacy-policy/\" target=\"_blank\">Privacy Policy</a> |\n    <a href=\"https://lfprojects.org/policies/terms-of-use/\" target=\"_blank\">Terms of Use</a>."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "scripts": [
    {
      "src": "/js/bootstrap.bundle.min.js",
      "async": false
    },
    {
      "src": "/js/effects.js",
      "async": false
    },
    {
      "src": "/js/ytlightbox.js",
      "async": false
    }
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
